using ReinforcedTypings.Tests.TestModels.Collections;
using ReinforcedTypings.Tests.TestModels.Consts;

namespace ReinforcedTypings.Tests;

public sealed class ReinforcedTypingsFluentConfigTests
{
	private const string ConstsRoot = "ReinforcedTypings.Tests.TestModels.Consts";

	private const string CollectionsRoot = "ReinforcedTypings.Tests.TestModels";

	#region TsConst - basic export modes

	[Fact]
	public void Configure_TsConstAll_ExportsUnignoredFieldsAsConstLiteral()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.TabSymbol = "\t";
			ctx.Global.NewLine = "\n";
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "BasicConstsAll.ts");

		// Field iteration order via reflection (GetFields) is not guaranteed, so assert on
		// content/structure rather than the full literal string.
		content.ShouldStartWith("export const BasicConstsAll = {\n");
		content.ShouldContain("\tTitle: 'Hello \\'World\\'',\n");
		content.ShouldContain("\tCount: 42,\n");
		content.ShouldContain("} as const;\n\n" +
			"export type BasicConstsAllKey = keyof typeof BasicConstsAll;\n" +
			"export type BasicConstsAllValue = (typeof BasicConstsAll)[BasicConstsAllKey];\n");
	}

	[Fact]
	public void Configure_TsConstSelected_OnlyExportsFieldsMarkedWithTsExportConst()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.TabSymbol = "\t";
			ctx.Global.NewLine = "\n";
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "BasicConstsSelected.ts");

		content.ShouldContain("Exported: 'keep',");
		content.ShouldNotContain("NotExported");
	}

	[Fact]
	public void Configure_TsConstAll_EmitsWarningCommentWhenEnabled()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = true;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "BasicConstsAll.ts");

		content.ShouldContain("This code was generated by a Reinforced.Typings tool.");
	}

	[Fact]
	public void Configure_TsConstEmptyAfterIgnoring_StillWritesEmptyObjectLiteral()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "EmptyConsts.ts");

		content.ShouldContain("export const EmptyConsts = {");
		content.ShouldContain("} as const;");
		content.ShouldNotContain("OnlyIgnored");
	}

	#endregion

	#region TsConst - value serialization

	[Fact]
	public void Configure_TsConstRichTypes_SerializesEveryFieldKindCorrectly()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "RichTypeConsts.ts");

		content.ShouldContain("Id: '11111111-1111-1111-1111-111111111111',");
		content.ShouldContain("CreatedAt: '2024-01-02T03:04:05.0000000Z',");
		content.ShouldContain("Day: '2024-01-02',");
		content.ShouldContain("Time: '03:04:05.0000000',");
		content.ShouldContain("Flag: true,");
		content.ShouldContain("Ratio: 3.14,");
		content.ShouldContain("Color: 1,"); // Plain enum (no [TsEnum]) always serializes numerically
		content.ShouldContain("Mode: 'Beta',"); // [TsEnum(UseString = true)]
		content.ShouldContain("Nothing: null,");
		content.ShouldContain("Numbers: [1, 2, 3],");
		content.ShouldContain("Tags: ['a', 'b'],");
		content.ShouldContain("Poco: { Label: 'x', Value: 7 },"); // Secret is [TsIgnore]d
	}

	[Fact]
	public void Configure_TsConstUnhandledStructType_FallsBackToObjectLiteralOfItsProperties()
	{
		// TimeSpan has no dedicated case in SerializeTsValue, so it recurses into
		// SerializeTsObjectLiteral over TimeSpan's own public properties.
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "TimeSpanConst.ts");

		content.ShouldContain("Duration: { ");
		content.ShouldContain("TotalMinutes: 90");
	}

	[Fact]
	public void Configure_TsConstCamelCaseForProperties_LowercasesFirstCharacterOfFieldNames()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.CamelCaseForProperties = true;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "CamelCaseConsts.ts");

		content.ShouldContain("pascalCaseFieldName: 'value',");
		content.ShouldNotContain("PascalCaseFieldName", Case.Sensitive);
	}

	[Fact]
	public void Configure_TsConstExportPureTypings_EmitsAmbientDeclareConstInsteadOfLiteral()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.ExportPureTypings = true;
			ctx.Global.RootNamespace = ConstsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "BasicConstsAll.ts");

		content.ShouldContain("export declare const BasicConstsAll: {");
		content.ShouldContain("readonly Title: 'Hello \\'World\\'';");
		content.ShouldContain("readonly Count: 42;");
		content.ShouldNotContain("as const");
		content.ShouldNotContain("Key = keyof");
	}

	#endregion

	#region TsConst - namespace / module wrapping

	[Fact]
	public void Configure_TsConstUseModulesFalse_WrapsInNamespaceMirroringCSharpNamespace()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = false;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = ConstsRoot; // strips "ReinforcedTypings.Tests.TestModels.Consts" leaving "Sub"
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Sub/NamespacedConsts.ts");

		content.ShouldContain("namespace Sub {");
		content.ShouldContain("export const NamespacedConsts = {");
		content.ShouldContain("Value: 'nested',");
		content.ShouldContain("}"); // closing brace for the namespace block
	}

	[Fact]
	public void Configure_TsConstUseModulesFalse_NoRootNamespace_NoTopLevelExport()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = false;
			ctx.Global.WriteWarningComment = false;
		});

		// Written into a namespace-mirroring subdirectory since there is no RootNamespace to strip.
		string content = RtTestHarness.ReadGenerated(outDir, "ReinforcedTypings/Tests/TestModels/Consts/BasicConstsAll.ts");

		content.ShouldContain("namespace ReinforcedTypings.Tests.TestModels.Consts {");
		content.ShouldContain("export const BasicConstsAll = {");
	}

	#endregion

	#region TsCollection - basic export modes

	[Fact]
	public void Configure_TsCollectionsAll_ExcludesIgnoredDictionaryAndScalarFields()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/BasicCollectionsAll.ts");

		content.ShouldContain("Names: ['a', 'b', 'c'] as string[],");
		content.ShouldNotContain("Ignored"); // [TsIgnoreCollection]
		content.ShouldNotContain("ADictionary"); // IDictionary is excluded
		content.ShouldNotContain("NotACollection"); // string field itself is excluded (not a collection)
		content.ShouldContain("export type BasicCollectionsAllCollectionsKey");
	}

	[Fact]
	public void Configure_TsCollectionsSelected_OnlyExportsFieldsMarkedWithTsExportCollection()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/BasicCollectionsSelected.ts");

		content.ShouldContain("Exported: [3, 4] as number[],");
		content.ShouldNotContain("NotExported");
	}

	[Fact]
	public void Configure_TsCollectionsWithNoEligibleFields_WritesNoFile()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		RtTestHarness.GeneratedFileExists(outDir, "Collections/EmptyEligibleCollections.ts").ShouldBeFalse();
	}

	#endregion

	#region TsCollection - referenced type resolution

	[Fact]
	public void Configure_TsCollectionsReferences_UseModulesTrue_ImportsRealGeneratedTypeNames()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/ReferenceCollections.ts");

		content.ShouldContain("import type { ExportedEnum } from './ExportedEnum';");
		content.ShouldContain("import type { IAutoIInterfaceModel } from './AutoIInterfaceModel';"); // AutoI (default true) prefixes with I
		content.ShouldContain("import type { PlainInterfaceModel } from './PlainInterfaceModel';"); // AutoI = false: no I prefix
		content.ShouldContain("import type { ExportedClassModel } from './ExportedClassModel';");

		content.ShouldContain("Enums: [0, 1] as ExportedEnum[],"); // Enum values serialize numerically (no [TsEnum(UseString = true)])
		content.ShouldContain("AutoIModels: [{ Name: 'one' }] as IAutoIInterfaceModel[],");
		content.ShouldContain("PlainModels: [{ Name: 'two' }] as PlainInterfaceModel[],");
		content.ShouldContain("ClassModels: [{ Name: 'three' }] as ExportedClassModel[],");
		content.ShouldContain("Unresolved: [{ Name: 'four' }] as any[],"); // Not exported by RT -> falls back to an "any" cast
	}

	[Fact]
	public void Configure_TsCollectionsReferences_UnresolvedToUnknown_FallsBackToUnknown()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.UnresolvedToUnknown = true;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/ReferenceCollections.ts");

		content.ShouldContain("Unresolved: ");
		content.ShouldContain("as unknown[],");
	}

	[Fact]
	public void Configure_TsCollectionsReferences_UseModulesFalse_QualifiesWithNamespaceInsteadOfImporting()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = false;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/ReferenceCollections.ts");

		content.ShouldNotContain("import type");
		content.ShouldContain("as Collections.ExportedEnum[],");
		content.ShouldContain("as Collections.IAutoIInterfaceModel[],");
	}

	[Fact]
	public void Configure_TsCollectionsCrossNamespace_UseModulesTrue_ComputesRelativeImportPath()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/CrossNamespaceCollections.ts");

		content.ShouldContain("import type { IOtherNamespaceModel } from './Other/OtherNamespaceModel';");

		// And the referenced type's own file must actually exist in that subdirectory.
		RtTestHarness.GeneratedFileExists(outDir, "Collections/Other/OtherNamespaceModel.ts").ShouldBeFalse(); // Only [TsInterface]-only types are handled by RT itself, not this hand-written generator
	}

	#endregion

	#region TsCollection - pure typings / camel case

	[Fact]
	public void Configure_TsCollectionsExportPureTypings_EmitsAmbientReadonlyArrayDeclaration()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.ExportPureTypings = true;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/BasicCollectionsAll.ts");

		content.ShouldContain("export declare const BasicCollectionsAllCollections: {");
		content.ShouldContain("readonly Names: readonly string[];");
		content.ShouldNotContain("as const");
	}

	[Fact]
	public void Configure_TsCollectionsCamelCaseForProperties_LowercasesFirstCharacterOfFieldNames()
	{
		string outDir = RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
			ctx.Global.WriteWarningComment = false;
			ctx.Global.CamelCaseForProperties = true;
			ctx.Global.RootNamespace = CollectionsRoot;
		});

		string content = RtTestHarness.ReadGenerated(outDir, "Collections/BasicCollectionsAll.ts");

		content.ShouldContain("names: ['a', 'b', 'c'] as string[],");
	}

	#endregion

	#region Valibot filtering branch (integration smoke test)

	[Fact]
	public void Configure_WithGenerateValibotSchemaTypesPresent_DoesNotThrow()
	{
		Should.NotThrow(() => RtTestHarness.RunConfigure(ctx =>
		{
			ctx.Global.UseModules = true;
		}));
	}

	#endregion
}
