using System.Reflection;
using CommonNetFuncs.ReinforcedTypings.Valibot;
using ReinforcedTypings.Tests.TestModels.Valibot;
using ReinforcedTypings.Tests.TestModels.Valibot.EdgeCases;

namespace ReinforcedTypings.Tests;

/// <summary>
/// Exercises <see cref="ValibotSchemaGenerator"/>'s schema-generation logic directly via its private
/// static <c>GenerateValibotSchema(Type)</c> method (invoked through reflection). This is the actual
/// business logic that builds the Valibot schema/labels source text. The public entry point
/// (<see cref="ValibotSchemaGenerator.GenerateNode"/>) and its <c>FindProjectDirectory</c> helper are
/// covered separately in <see cref="ValibotSchemaGeneratorNodeTests"/>, which sandboxes their
/// filesystem side effects.
/// </summary>
public sealed class ValibotSchemaGeneratorTests
{
	private static string GenerateSchema(Type type)
	{
		MethodInfo method = typeof(ValibotSchemaGenerator).GetMethod("GenerateValibotSchema", BindingFlags.NonPublic | BindingFlags.Static)
			?? throw new InvalidOperationException("GenerateValibotSchema method not found via reflection.");

		return (string)method.Invoke(null, [type])!;
	}

	[Fact]
	public void GenerateValibotSchema_EmitsHeaderImportAndInputType()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("This code was generated by the ValibotSchemaGenerator.");
		schema.ShouldContain("import * as v from 'valibot';");
		schema.ShouldContain("export const FullValidationModelSchema = v.object({");
		schema.ShouldContain("});");
		schema.ShouldContain("export type FullValidationModelInput = v.InferInput<typeof FullValidationModelSchema>;");
		schema.ShouldContain("export const FullValidationModelLabels: Record<string, string> = {");
	}

	[Fact]
	public void GenerateValibotSchema_RequiredNonNullableString_NoOptionalOrNullableWrapping()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Name: v.pipe(v.string(), v.maxLength(50)),");
	}

	[Fact]
	public void GenerateValibotSchema_OptionalNullableStringWithStringLength_WrapsOptionalNullable()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Nickname: v.optional(v.nullable(v.pipe(v.string(), v.minLength(3), v.maxLength(20)))),");
	}

	[Fact]
	public void GenerateValibotSchema_RangeOnNonNullableInt_WrapsOptionalWithMinMaxValue()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Age: v.optional(v.pipe(v.number(), v.minValue(1), v.maxValue(100))),");
	}

	[Fact]
	public void GenerateValibotSchema_NonNullableStringWithoutRequired_IsNeverWrappedOptional()
	{
		// Strings are special-cased: even without [Required], a bare (non-nullable) string property
		// is not wrapped in v.optional(...) since propType == typeof(string) is explicitly excluded.
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Code: v.pipe(v.string(), v.regex(/^[A-Z]+$/)),");
		schema.ShouldContain("Email: v.pipe(v.string(), v.email('The {0} field is not a valid e-mail address.')),");
	}

	[Theory]
	[InlineData("Website: v.optional(v.nullable(v.pipe(v.string(), v.url('The {0} field is not a valid fully-qualified http, https, or ftp URL.')))),")]
	[InlineData("PhoneNumber: v.optional(v.nullable(v.pipe(v.string(), v.regex(/^\\+?[\\d\\s\\-().]+$/, 'The {0} field is not a valid phone number.')))),")]
	[InlineData("CardNumber: v.optional(v.nullable(v.pipe(v.string(), v.creditCard('The {0} field is not a valid credit card number.')))),")]
	public void GenerateValibotSchema_NullableStringValidators_ProduceExpectedPipe(string expectedLine)
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain(expectedLine);
	}

	[Fact]
	public void GenerateValibotSchema_CustomDenyCharactersAndDenyRegex_ProduceRegexPipes()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("SafeText: v.pipe(v.string(), v.regex(/^[^<>]*$/)),");
		schema.ShouldContain("NoBadWord: v.pipe(v.string(), v.regex(/^(?!.*bad).*$/)),");
	}

	[Fact]
	public void GenerateValibotSchema_AllowedNullableValues_ProducesUnionOfLiterals()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Choice: v.optional(v.nullable(v.pipe(v.string(), v.union([v.literal('A'), v.literal('B'), v.literal('C')])))),");
	}

	[Theory]
	[InlineData("Tags: v.optional(v.array(v.pipe(v.string(), v.maxLength(10, 'Too many tags')))),")] // ListMaxLength (with an ErrorMessage)
	[InlineData("Codes: v.optional(v.array(v.pipe(v.string(), v.minLength(2), v.maxLength(15)))),")] // ListStringLength
	[InlineData("Scores: v.optional(v.array(v.pipe(v.number(), v.minValue(0), v.maxValue(10)))),")] // ListRange
	[InlineData("Numeric: v.optional(v.array(v.pipe(v.string(), v.regex(/^[0-9]+$/)))),")] // ListRegularExpression
	[InlineData("Clean: v.optional(v.array(v.pipe(v.string(), v.regex(/^[^!@#]*$/)))),")] // ListDenyCharacters
	[InlineData("GoodWords: v.optional(v.array(v.pipe(v.string(), v.regex(/^(?!.*bad).*$/)))),")] // ListDenyRegularExpression
	public void GenerateValibotSchema_ListItemLevelValidators_EmbedPipeIntoArrayElementSchema(string expectedLine)
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain(expectedLine);
	}

	[Theory]
	[InlineData("ExternalId: v.optional(v.string()),")] // Guid
	[InlineData("CreatedOn: v.optional(v.string()),")] // DateTime
	[InlineData("BirthDate: v.optional(v.string()),")] // DateOnly
	[InlineData("Status: v.optional(v.number()),")] // enum
	[InlineData("OptionalNumber: v.optional(v.nullable(v.number())),")] // nullable value type
	[InlineData("RequiredNumber: v.optional(v.number()),")] // non-nullable value type without [Required]
	public void GenerateValibotSchema_ScalarAndEnumTypes_MapToExpectedBaseSchema(string expectedLine)
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain(expectedLine);
	}

	[Fact]
	public void GenerateValibotSchema_NestedComplexProperty_RecursesIntoInlineObjectSchema()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Nested: v.optional(v.object({Label: v.string(), RequiredChild: v.string()})),");
	}

	[Fact]
	public void GenerateValibotSchema_TsIgnoredProperty_IsExcludedFromSchemaAndLabels()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldNotContain("Ignored:");
	}

	[Fact]
	public void GenerateValibotSchema_DisplayNameAttribute_OverridesDefaultLabel()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("Name: 'Full Name',");
	}

	[Fact]
	public void GenerateValibotSchema_NoDisplayName_DerivesLabelFromSplitPascalCase()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("PhoneNumber: 'Phone Number',");
		schema.ShouldContain("CardNumber: 'Card Number',");
	}

	[Fact]
	public void GenerateValibotSchema_SelfReferencingType_BreaksCycleWithAny()
	{
		string schema = GenerateSchema(typeof(CyclicModel));

		schema.ShouldContain("Name: v.string(),");
		schema.ShouldContain("Self: v.optional(v.nullable(v.any())),");
	}

	[Fact]
	public void GenerateValibotSchema_SubsetOfAttribute_InheritsValidationFromSourceType()
	{
		// BoundSourceModel itself carries no validation attributes on Code; they should be pulled from
		// SourceModel via [SubsetOf(typeof(SourceModel))].
		string schema = GenerateSchema(typeof(BoundSourceModel));

		schema.ShouldContain("Code: v.pipe(v.string(), v.maxLength(5)),");
	}

	[Fact]
	public void GenerateValibotSchema_SubsetOfAttributeWithoutSourceTypeProperty_FallsBackToConstructorArgument()
	{
		// EdgeBoundSourceModel's [SubsetOf] attribute has no "SourceType" property, forcing
		// ResolveSourceType to read the source type from the attribute's constructor argument instead.
		string schema = GenerateSchema(typeof(EdgeBoundSourceModel));

		schema.ShouldContain("Code: v.pipe(v.string(), v.maxLength(7)),");
	}

	[Fact]
	public void GenerateValibotSchema_MinLengthAttribute_ProducesMinLengthPipe()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("MinLenText: v.pipe(v.string(), v.minLength(3)),");
	}

	[Fact]
	public void GenerateValibotSchema_RequiredNullableProperty_WrapsNullableWithoutOptional()
	{
		// isRequired && isNullable: the field must be provided but its value may still be null, so it's
		// wrapped in v.nullable(...) but NOT v.optional(...).
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("RequiredNullableString: v.nullable(v.string()),");
	}

	[Fact]
	public void GenerateValibotSchema_DenyCharactersWithRegexSpecialChars_EscapesThemInCharacterClass()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("StrictText: v.pipe(v.string(), v.regex(/^[^\\]\\^\\-]*$/)),");
	}

	[Fact]
	public void GenerateValibotSchema_AllowedNullableValuesWithNoValues_ProducesNoUnionPipe()
	{
		// Property present but empty (values.Length == 0): GetAllowedValuesPipe returns null, so no
		// v.union(...) pipe is added at all - distinct from the "property missing entirely" case below.
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("EmptyChoice: v.optional(v.nullable(v.string())),");
	}

	[Fact]
	public void GenerateValibotSchema_AllowedNullableValuesWithNonStringValues_ProducesUnquotedLiterals()
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain("NumericChoice: v.optional(v.nullable(v.pipe(v.number(), v.union([v.literal(1), v.literal(2), v.literal(3)])))),");
	}

	[Theory]
	[InlineData("NumbersArray: v.optional(v.array(v.number())),")] // raw C# array (not List<>) with no item-level pipe
	[InlineData("IListProp: v.optional(v.array(v.string())),")] // IList<T> without an item-level pipe
	[InlineData("IEnumerableProp: v.optional(v.array(v.number())),")] // IEnumerable<T> without an item-level pipe
	[InlineData("ICollectionProp: v.optional(v.array(v.string())),")] // ICollection<T> without an item-level pipe
	[InlineData("Price: v.optional(v.number()),")] // double
	[InlineData("Flag: v.optional(v.boolean()),")] // bool
	[InlineData("Misc: v.optional(v.nullable(v.any())),")] // System-namespaced type falls through to the v.any() fallback
	public void GenerateValibotSchema_RemainingScalarAndCollectionShapes_MapToExpectedBaseSchema(string expectedLine)
	{
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldContain(expectedLine);
	}

	[Fact]
	public void GenerateValibotSchema_TsIgnoredPropertyOnNestedType_IsExcludedFromInlineObjectSchema()
	{
		// NestedValibotModel.HiddenChild carries [TsIgnore]; BuildInlineObjectSchema (used for nested
		// complex properties) must skip it just like GenerateValibotSchema's own top-level loop does.
		string schema = GenerateSchema(typeof(FullValidationModel));

		schema.ShouldNotContain("HiddenChild");
	}

	[Theory]
	[InlineData("MissingLength: v.string(),")] // broken [ListMaxLength]: missing "Length" property -> null pipe
	[InlineData("MissingLengths: v.string(),")] // broken [ListStringLength]
	[InlineData("MissingRange: v.string(),")] // broken [ListRange]
	[InlineData("MissingPattern: v.string(),")] // broken [ListRegularExpression]
	[InlineData("MissingDenyChars: v.string(),")] // broken [ListDenyCharacters]
	[InlineData("MissingDenyPattern: v.string(),")] // broken [ListDenyRegularExpression]
	[InlineData("MissingDenyCharsOuter: v.string(),")] // broken [DenyCharacters]
	[InlineData("MissingDenyPatternOuter: v.string(),")] // broken [DenyRegularExpression]
	[InlineData("MissingValues: v.optional(v.nullable(v.string())),")] // broken [AllowedNullableValues]: missing "Values" property
	public void GenerateValibotSchema_BrokenCustomAttributesMissingExpectedProperty_ProduceNoPipe(string expectedLine)
	{
		// Every property on EdgeCaseAttributeModel carries a custom attribute matched by type name but
		// lacking the property Get*Pipe reflects over, exercising each method's null-fallback branch.
		string schema = GenerateSchema(typeof(EdgeCaseAttributeModel));

		schema.ShouldContain(expectedLine);
	}

	[Fact]
	public void GetAttrErrorMessage_ValidationAttributeWithErrorMessage_ReturnsItDirectly()
	{
		MethodInfo method = typeof(ValibotSchemaGenerator).GetMethod("GetAttrErrorMessage", BindingFlags.NonPublic | BindingFlags.Static)
			?? throw new InvalidOperationException("GetAttrErrorMessage method not found via reflection.");

		ReinforcedTypings.Tests.TestModels.Valibot.ListMaxLengthAttribute withMessage = new(5) { ErrorMessage = "boom" };

		string? result = (string?)method.Invoke(null, [withMessage]);

		result.ShouldBe("boom");
	}

	[Fact]
	public void GetAttrErrorMessage_ValidationAttributeWithoutErrorMessage_FallsBackToReflectionAndReturnsNull()
	{
		MethodInfo method = typeof(ValibotSchemaGenerator).GetMethod("GetAttrErrorMessage", BindingFlags.NonPublic | BindingFlags.Static)
			?? throw new InvalidOperationException("GetAttrErrorMessage method not found via reflection.");

		ReinforcedTypings.Tests.TestModels.Valibot.ListMaxLengthAttribute withoutMessage = new(5);

		string? result = (string?)method.Invoke(null, [withoutMessage]);

		result.ShouldBeNull();
	}
}
