using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text;
using Reinforced.Typings;
using Reinforced.Typings.Ast;
using Reinforced.Typings.Generators;

namespace CommonNetFuncs.ReinforcedTypings.Valibot;

/// <summary>
/// Custom Reinforced.Typings code generator that produces both the standard TypeScript interface
/// and a companion Valibot validation schema derived from C# DataAnnotations and
/// CommonNetFuncs.Web.Common.ValidationAttributes.
///
/// The schema is written as a companion .schema.ts file next to the generated interface file
/// (in the TypeScriptModels/ directory). The existing PostBuild target copies it to front-end/src/dbmodels/Generated/.
/// </summary>
public sealed class ValibotSchemaGenerator : InterfaceCodeGenerator
{
	private static string? outputDirectory;

	public override RtInterface GenerateNode(Type element, RtInterface result, TypeResolver resolver)
	{
		// Let the base generator produce the standard interface AST
		RtInterface node = base.GenerateNode(element, result, resolver);
		if (node == null)
		{
			return null!;
		}

		// Defense-in-depth: skip schema generation for types that were not explicitly opted in.
		// The fluent config already filters to [GenerateValibotSchema] types; this guard
		// makes the generator safe if it is ever applied programmatically without the filter.
		if (element.GetCustomAttribute<GenerateValibotSchemaAttribute>() == null)
		{
			return node;
		}

		// Resolve the output directory from RT's target directory (set once)
		if (outputDirectory == null)
		{
			// The TypeScriptModels directory is where RT writes files — derive it from the assembly location
			string assemblyDir = Path.GetDirectoryName(element.Assembly.Location) ?? "";

			// Find the project directory containing TypeScriptModels
			string? projectDir = FindProjectDirectory(assemblyDir);
			if (projectDir != null)
			{
				outputDirectory = Path.Combine(projectDir, "TypeScriptModels");
				Directory.CreateDirectory(outputDirectory);
			}
		}

		// Generate and write the companion schema file
		if (outputDirectory != null)
		{
			string schemaCode = GenerateValibotSchema(element);
			if (!string.IsNullOrWhiteSpace(schemaCode))
			{
				string schemaPath = Path.Combine(outputDirectory, $"{element.Name}.schema.ts");
				File.WriteAllText(schemaPath, schemaCode);
			}
		}

		return node;
	}

	private static string? FindProjectDirectory(string startDir)
	{
		string? dir = startDir;
		// Walk up looking for the TypeScriptModels directory or the .csproj
		while (dir != null)
		{
			if (Directory.Exists(Path.Combine(dir, "TypeScriptModels")) || Directory.GetFiles(dir, "*.csproj").Length > 0)
			{
				return dir;
			}
			dir = Path.GetDirectoryName(dir);
		}
		return null;
	}

	private static string GenerateValibotSchema(Type type)
	{
		// Resolve the source type for validation attributes
		// BoundX types use [SubsetOf(typeof(SourceType))] and inherit validation from the parent
		Type sourceType = ResolveSourceType(type);
		string typeName = type.Name;

		StringBuilder sb = new();
		sb.AppendLine("//     This code was generated by the ValibotSchemaGenerator.");
		sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
		sb.AppendLine("//     the code is regenerated.");
		sb.AppendLine();
		sb.AppendLine("import * as v from 'valibot';");
		sb.AppendLine();
		sb.AppendLine($"export const {typeName}Schema = v.object({{");

		PropertyInfo[] properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);

		// Seed the ancestor set with the root type so cycles back to it are detected
		HashSet<Type> ancestors = [type];

		// Also build a labels map for DisplayName attributes
		StringBuilder labelsSb = new();
		labelsSb.AppendLine($"export const {typeName}Labels: Record<string, string> = {{");

		foreach (PropertyInfo prop in properties)
		{
			// Skip navigation/ignored properties
			if (prop.GetCustomAttribute<Reinforced.Typings.Attributes.TsIgnoreAttribute>() != null)
			{
				continue;
			}

			// Get validation attributes from the source type (parent) if available
			PropertyInfo? sourceProp = sourceType != type
				? sourceType.GetProperty(prop.Name, BindingFlags.Public | BindingFlags.Instance)
				: null;

			PropertyInfo effectiveProp = sourceProp ?? prop;

			// Use source property attributes if available, otherwise use the property's own attributes
			IEnumerable<ValidationAttribute> validationAttrs = effectiveProp
				.GetCustomAttributes(true)
				.OfType<ValidationAttribute>();

			// Also check for custom CommonNetFuncs validation attributes via base class name matching
			IEnumerable<Attribute> allAttrs = effectiveProp.GetCustomAttributes(true).OfType<Attribute>();

			string schema = BuildPropertySchema(prop, validationAttrs, allAttrs, ancestors);
			sb.AppendLine($"\t{prop.Name}: {schema},");

			// Extract DisplayName
			DisplayNameAttribute? displayName = effectiveProp.GetCustomAttribute<DisplayNameAttribute>(true);
			string label = displayName?.DisplayName ?? SplitPascalCase(prop.Name);
			labelsSb.AppendLine($"\t{prop.Name}: '{EscapeJsString(label)}',");
		}

		sb.AppendLine("});");
		sb.AppendLine();
		sb.AppendLine($"export type {typeName}Input = v.InferInput<typeof {typeName}Schema>;");
		sb.AppendLine();

		labelsSb.AppendLine("};");
		sb.Append(labelsSb);

		return sb.ToString();
	}

	private static string SplitPascalCase(string name)
	{
		StringBuilder result = new();
		for (int i = 0; i < name.Length; i++)
		{
			if (i > 0 && char.IsUpper(name[i]) && !char.IsUpper(name[i - 1]))
			{
				result.Append(' ');
			}
			result.Append(name[i]);
		}
		return result.ToString();
	}

	private static string EscapeJsString(string s)
	{
		return s.Replace("\\", "\\\\").Replace("'", "\\'");
	}
	/// <summary>
	/// Returns the Valibot message argument for an optional error-message parameter.
	/// When <paramref name="leadingComma"/> is <c>true</c> (default) the result is prefixed with a comma,
	/// suitable for validators that already have a required first arg: <c>v.maxLength(10, 'Too long')</c>.
	/// When <c>false</c> the quoted string is returned alone: <c>v.email('Invalid')</c>.
	/// Returns an empty string when <paramref name="message"/> is null or whitespace.
	/// </summary>
	private static string ErrorMessageArg(string? message, bool leadingComma = true)
	{
		if (string.IsNullOrWhiteSpace(message))
		{
			return string.Empty;
		}

		string escaped = EscapeJsString(message);
		return leadingComma ? $", '{escaped}'" : $"'{escaped}'";
	}

	/// <summary>
	/// Returns the <c>ErrorMessage</c> from a validation attribute.
	/// Tries the strongly-typed <see cref="ValidationAttribute"/> base first, then falls back to
	/// reflection for custom attribute types that declare their own <c>ErrorMessage</c> property.
	/// </summary>
	private static string? GetAttrErrorMessage(Attribute attr)
	{
		if (attr is ValidationAttribute validationAttribute && !string.IsNullOrWhiteSpace(validationAttribute.ErrorMessage))
		{
			return validationAttribute.ErrorMessage;
		}
		return attr.GetType().GetProperty("ErrorMessage")?.GetValue(attr) as string;
	}
	private static string BuildPropertySchema(PropertyInfo prop, IEnumerable<ValidationAttribute> validationAttrs, IEnumerable<Attribute> allAttrs, HashSet<Type> ancestors)
	{
		Type propType = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;
		bool isNullable = Nullable.GetUnderlyingType(prop.PropertyType) != null || !prop.PropertyType.IsValueType || (prop.PropertyType.IsGenericType && prop.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>));

		// For reference types (string, arrays, etc.), check if nullable
		if (!prop.PropertyType.IsValueType)
		{
			NullabilityInfoContext nullContext = new();
			NullabilityInfo nullInfo = nullContext.Create(prop);
			isNullable = nullInfo.WriteState != NullabilityState.NotNull;
		}

		// Collect outer-level pipe validators (applied to the property value itself)
		List<string> outerPipes = [];
		// Collect item-level pipe validators (applied to each element of array/list properties)
		List<string> itemPipes = [];

		foreach (ValidationAttribute attr in validationAttrs)
		{
			string? pipe = attr switch
			{
				RequiredAttribute => null, // Handled by nullable/optional logic
				MaxLengthAttribute maxLen => $"v.maxLength({maxLen.Length}{ErrorMessageArg(maxLen.ErrorMessage)})",
				MinLengthAttribute minLen => $"v.minLength({minLen.Length}{ErrorMessageArg(minLen.ErrorMessage)})",
				StringLengthAttribute strLen => BuildStringLengthPipe(strLen),
				RangeAttribute range => BuildRangePipe(range),
				RegularExpressionAttribute regex => $"v.regex(/{regex.Pattern}/{ErrorMessageArg(regex.ErrorMessage)})",
				EmailAddressAttribute email => $"v.email({ErrorMessageArg(email.ErrorMessage, leadingComma: false)})",
				UrlAttribute url => $"v.url({ErrorMessageArg(url.ErrorMessage, leadingComma: false)})",
				PhoneAttribute phone => $"v.regex(/^\\+?[\\d\\s\\-().]+$/{ErrorMessageArg(phone.ErrorMessage)})",
				CreditCardAttribute card => $"v.creditCard({ErrorMessageArg(card.ErrorMessage, leadingComma: false)})",
				_ => null
			};

			if (pipe != null)
			{
				outerPipes.Add(pipe);
			}
		}

		// Handle custom CommonNetFuncs.Web.Common.ValidationAttributes.
		// List* attributes produce item-level pipes; others produce outer-level pipes.
		foreach (Attribute attr in allAttrs)
		{
			(bool isItemLevel, string? pipe) = GetCustomAttributePipe(attr);
			if (pipe != null)
			{
				if (isItemLevel)
				{
					itemPipes.Add(pipe);
				}
				else
				{
					outerPipes.Add(pipe);
				}
			}
		}

		// Handle Required attribute specifically
		bool isRequired = validationAttrs.Any(x => x is RequiredAttribute);

		// Build base schema. For array/list types with item validators, embed the validators
		// into the element schema: v.array(v.pipe(itemType, ...itemPipes))
		Type? itemType = GetArrayItemType(propType);
		string baseSchema;
		if (itemType != null && itemPipes.Count > 0)
		{
			string itemBaseSchema = GetBaseSchema(itemType, ancestors);
			string itemSchema = $"v.pipe({itemBaseSchema}, {string.Join(", ", itemPipes)})";
			baseSchema = $"v.array({itemSchema})";
		}
		else
		{
			baseSchema = GetBaseSchema(propType, ancestors);
		}

		// Build the final schema
		string schema;
		if (outerPipes.Count > 0)
		{
			schema = $"v.pipe({baseSchema}, {string.Join(", ", outerPipes)})";
		}
		else
		{
			schema = baseSchema;
		}

		// Wrap in optional/nullable as appropriate
		if (!isRequired && isNullable)
		{
			schema = $"v.optional(v.nullable({schema}))";
		}
		else if (isNullable) // isRequired && isNullable: field must be provided but its value may be null
		{
			schema = $"v.nullable({schema})";
		}
		else if (!isRequired && propType != typeof(string))
		{
			schema = $"v.optional({schema})";
		}

		return schema;
	}

	private static string GetBaseSchema(Type propType, HashSet<Type> ancestors)
	{
		// Check if it's an array or list type
		if (propType.IsArray)
		{
			Type elementType = propType.GetElementType()!;
			return $"v.array({GetBaseSchema(elementType, ancestors)})";
		}

		if (propType.IsGenericType)
		{
			Type genericDef = propType.GetGenericTypeDefinition();
			if (genericDef == typeof(List<>) || genericDef == typeof(IList<>) || genericDef == typeof(IEnumerable<>) || genericDef == typeof(ICollection<>))
			{
				Type elementType = propType.GetGenericArguments()[0];
				return $"v.array({GetBaseSchema(elementType, ancestors)})";
			}
		}

		if (propType == typeof(string))
		{
			return "v.string()";
		}

		if (propType == typeof(int) || propType == typeof(long) || propType == typeof(short) || propType == typeof(byte) || propType == typeof(uint) || propType == typeof(ulong))
		{
			return "v.number()";
		}

		if (propType == typeof(float) || propType == typeof(double) || propType == typeof(decimal))
		{
			return "v.number()";
		}

		if (propType == typeof(bool))
		{
			return "v.boolean()";
		}

		if (propType == typeof(DateTime) || propType == typeof(DateTimeOffset) || propType == typeof(DateOnly))
		{
			return "v.string()"; // Dates come as strings in JSON
		}

		if (propType == typeof(Guid))
		{
			return "v.string()";
		}

		if (propType.IsEnum)
		{
			return "v.number()"; // Enums are typically numbers in TS
		}

		// Recurse into complex domain types (non-system classes with public properties)
		if (propType.IsClass && propType.Namespace != null && !propType.Namespace.StartsWith("System", StringComparison.Ordinal) && !propType.Namespace.StartsWith("Microsoft", StringComparison.Ordinal))
		{
			if (ancestors.Contains(propType))
			{
				return "v.any()"; // Cycle detected — break recursion
			}

			ancestors.Add(propType);
			string objectSchema = BuildInlineObjectSchema(propType, ancestors);
			ancestors.Remove(propType);
			return objectSchema;
		}

		// Fallback for any remaining unrecognized types
		return "v.any()";
	}

	/// <summary>
	/// Builds a compact inline <c>v.object({...})</c> schema for a complex property type.
	/// Validation attributes on the nested type's properties are honoured.
	/// Cycle detection is enforced by the caller via <paramref name="ancestors"/>.
	/// </summary>
	private static string BuildInlineObjectSchema(Type type, HashSet<Type> ancestors)
	{
		PropertyInfo[] properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);

		StringBuilder sb = new();
		sb.Append("v.object({");

		bool first = true;
		foreach (PropertyInfo prop in properties)
		{
			if (prop.GetCustomAttribute<Reinforced.Typings.Attributes.TsIgnoreAttribute>() != null)
			{
				continue;
			}

			IEnumerable<ValidationAttribute> validationAttrs = prop.GetCustomAttributes(true).OfType<ValidationAttribute>();
			IEnumerable<Attribute> allAttrs = prop.GetCustomAttributes(true).OfType<Attribute>();

			if (!first)
			{
				sb.Append(", ");
			}

			sb.Append($"{prop.Name}: {BuildPropertySchema(prop, validationAttrs, allAttrs, ancestors)}");
			first = false;
		}

		sb.Append("})");
		return sb.ToString();
	}

	/// <summary>Returns the element type of an array or generic list/collection type, or null for scalar types.
	/// The returned type has Nullable unwrapped so it can be passed directly to <see cref="GetBaseSchema"/>.</summary>
	private static Type? GetArrayItemType(Type type)
	{
		Type? itemType = null;

		if (type.IsArray)
		{
			itemType = type.GetElementType();
		}
		else if (type.IsGenericType)
		{
			Type genericDef = type.GetGenericTypeDefinition();
			if (genericDef == typeof(List<>) || genericDef == typeof(IList<>) || genericDef == typeof(IEnumerable<>) || genericDef == typeof(ICollection<>))
			{
				itemType = type.GetGenericArguments()[0];
			}
		}

		// Unwrap Nullable<T> so GetBaseSchema can recognize the underlying primitive
		return itemType != null ? (Nullable.GetUnderlyingType(itemType) ?? itemType) : null;
	}

	private static string BuildStringLengthPipe(StringLengthAttribute attr)
	{
		string msgArg = ErrorMessageArg(attr.ErrorMessage);
		List<string> parts = [];
		if (attr.MinimumLength > 0)
		{
			parts.Add($"v.minLength({attr.MinimumLength}{msgArg})");
		}

		parts.Add($"v.maxLength({attr.MaximumLength}{msgArg})");
		return string.Join(", ", parts);
	}

	private static string BuildRangePipe(RangeAttribute attr)
	{
		string msgArg = ErrorMessageArg(attr.ErrorMessage);
		List<string> parts = [];
		if (attr.Minimum != null)
		{
			parts.Add($"v.minValue({attr.Minimum}{msgArg})");
		}

		if (attr.Maximum != null)
		{
			parts.Add($"v.maxValue({attr.Maximum}{msgArg})");
		}

		return string.Join(", ", parts);
	}

	/// <summary>
	/// Returns (isItemLevel, pipe?) for custom validation attributes.
	/// <c>isItemLevel = true</c> means the pipe targets each element of an array/list and will be
	/// embedded into the element schema rather than piped on the array itself.
	/// </summary>
	private static (bool isItemLevel, string? pipe) GetCustomAttributePipe(Attribute attr)
	{
		// Handle CommonNetFuncs.Web.Common.ValidationAttributes by type name.
		// This allows the generator to work even when the exact types aren't directly referenced.
		string typeName = attr.GetType().Name;

		return typeName switch
		{
			"ListMaxLengthAttribute" => (true, GetListMaxLengthItemPipe(attr)),
			"ListStringLengthAttribute" => (true, GetListStringLengthItemPipe(attr)),
			"ListRangeAttribute" => (true, GetListRangeItemPipe(attr)),
			"ListRegularExpressionAttribute" => (true, GetListRegexItemPipe(attr)),
			"ListDenyCharactersAttribute" => (true, GetListDenyCharsItemPipe(attr)),
			"ListDenyRegularExpressionAttribute" => (true, GetListDenyRegexItemPipe(attr)),
			"DenyCharactersAttribute" => (false, GetDenyCharsPipe(attr)),
			"DenyRegularExpressionAttribute" => (false, GetDenyRegexPipe(attr)),
			"AllowedNullableValuesAttribute" => (false, GetAllowedValuesPipe(attr)),
			_ => (false, null)
		};
	}

	// Item-level pipe methods: these return validators that are embedded into the array element schema,
	// producing e.g. v.array(v.pipe(v.string(), v.maxLength(50))) instead of the invalid v.every(...).

	private static string? GetListMaxLengthItemPipe(Attribute attr)
	{
		PropertyInfo? lengthProp = attr.GetType().GetProperty("Length");
		if (lengthProp?.GetValue(attr) is int length)
		{
			return $"v.maxLength({length}{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetListStringLengthItemPipe(Attribute attr)
	{
		PropertyInfo? maxProp = attr.GetType().GetProperty("MaximumLength");
		PropertyInfo? minProp = attr.GetType().GetProperty("MinimumLength");
		int? max = maxProp?.GetValue(attr) as int?;
		int? min = minProp?.GetValue(attr) as int?;
		string msgArg = ErrorMessageArg(GetAttrErrorMessage(attr));

		List<string> pipes = [];
		if (min.HasValue && min.Value > 0)
		{
			pipes.Add($"v.minLength({min.Value}{msgArg})");
		}

		if (max.HasValue)
		{
			pipes.Add($"v.maxLength({max.Value}{msgArg})");
		}
		return pipes.Count > 0 ? string.Join(", ", pipes) : null;
	}

	private static string? GetListRangeItemPipe(Attribute attr)
	{
		PropertyInfo? minProp = attr.GetType().GetProperty("Minimum");
		PropertyInfo? maxProp = attr.GetType().GetProperty("Maximum");
		object? min = minProp?.GetValue(attr);
		object? max = maxProp?.GetValue(attr);
		string msgArg = ErrorMessageArg(GetAttrErrorMessage(attr));

		List<string> pipes = [];
		if (min != null)
		{
			pipes.Add($"v.minValue({min}{msgArg})");
		}

		if (max != null)
		{
			pipes.Add($"v.maxValue({max}{msgArg})");
		}

		return pipes.Count > 0 ? string.Join(", ", pipes) : null;
	}

	private static string? GetListRegexItemPipe(Attribute attr)
	{
		PropertyInfo? patternProp = attr.GetType().GetProperty("Pattern");
		if (patternProp?.GetValue(attr) is string pattern)
		{
			return $"v.regex(/{pattern}/{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetListDenyCharsItemPipe(Attribute attr)
	{
		PropertyInfo? charsProp = attr.GetType().GetProperty("DeniedCharacters") ?? attr.GetType().GetProperty("Characters");
		if (charsProp?.GetValue(attr) is string chars)
		{
			return $"v.regex(/^[^{EscapeRegexChars(chars)}]*$/{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetListDenyRegexItemPipe(Attribute attr)
	{
		PropertyInfo? patternProp = attr.GetType().GetProperty("Pattern");
		if (patternProp?.GetValue(attr) is string pattern)
		{
			return $"v.regex(/^(?!.*{pattern}).*$/{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetDenyCharsPipe(Attribute attr)
	{
		PropertyInfo? charsProp = attr.GetType().GetProperty("DeniedCharacters") ?? attr.GetType().GetProperty("Characters");
		if (charsProp?.GetValue(attr) is string chars)
		{
			return $"v.regex(/^[^{EscapeRegexChars(chars)}]*$/{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetDenyRegexPipe(Attribute attr)
	{
		PropertyInfo? patternProp = attr.GetType().GetProperty("Pattern");
		if (patternProp?.GetValue(attr) is string pattern)
		{
			return $"v.regex(/^(?!.*{pattern}).*$/{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}

		return null;
	}

	private static string? GetAllowedValuesPipe(Attribute attr)
	{
		PropertyInfo? valuesProp = attr.GetType().GetProperty("AllowedValues") ?? attr.GetType().GetProperty("Values");
		if (valuesProp?.GetValue(attr) is object[] values && values.Length > 0)
		{
			string literals = string.Join(", ", values.Select(x => x is string str ? $"v.literal('{str}')" : $"v.literal({x})"));
			return $"v.union([{literals}]{ErrorMessageArg(GetAttrErrorMessage(attr))})";
		}
		return null;
	}

	private static Type ResolveSourceType(Type type)
	{
		// Look for [SubsetOf(typeof(X))] attribute
		Attribute? subsetAttr = type.GetCustomAttributes(false)
			.OfType<Attribute>()
			.FirstOrDefault(x => x.GetType().Name == "SubsetOfAttribute");

		if (subsetAttr != null)
		{
			// Try SourceType property first
			PropertyInfo? typeProp = subsetAttr.GetType().GetProperty("SourceType");

			if (typeProp != null)
			{
				object? val = typeProp.GetValue(subsetAttr);
				if (val is Type sourceType)
				{
					return sourceType;
				}
			}

			// Fallback: look at constructor arguments via CustomAttributeData
			CustomAttributeData? attrData = type.CustomAttributes.FirstOrDefault(x => x.AttributeType.Name == "SubsetOfAttribute");

			if (attrData?.ConstructorArguments.Count > 0 && attrData.ConstructorArguments[0].Value is Type ctorSourceType)
			{
				return ctorSourceType;
			}
		}

		return type;
	}
	
	private static string EscapeRegexChars(string chars)
	{
		// Escape characters that are special in regex character classes
		StringBuilder sb = new();
		foreach (char c in chars)
		{
			if (c is ']' or '^' or '-')
			{
				sb.Append('\\');
			}
			sb.Append(c);
		}
		return sb.ToString();
	}
}
