namespace CommonNetFuncs.Excel.Common;

#pragma warning disable CRR0048 // The type name does not correspond to the file name
public enum EStyle
{
    Header,
    HeaderThickTop,
    Body,
    Error,
    Blackout,
    Whiteout,
    Custom,
    ImageBackground
}

public enum EFont
{
    Default,
    Header,
    Whiteout,
    ImageBackground
}

public enum ETableStyle
{
    TableStyleDark1,
    TableStyleDark2,
    TableStyleDark3,
    TableStyleDark4,
    TableStyleDark5,
    TableStyleDark6,
    TableStyleDark7,
    TableStyleDark8,
    TableStyleDark9,
    TableStyleDark10,
    TableStyleDark11,
    TableStyleLight1,
    TableStyleLight2,
    TableStyleLight3,
    TableStyleLight4,
    TableStyleLight5,
    TableStyleLight6,
    TableStyleLight7,
    TableStyleLight8,
    TableStyleLight9,
    TableStyleLight10,
    TableStyleLight11,
    TableStyleLight12,
    TableStyleLight13,
    TableStyleLight14,
    TableStyleLight15,
    TableStyleLight16,
    TableStyleLight17,
    TableStyleLight18,
    TableStyleLight19,
    TableStyleLight20,
    TableStyleLight21,
    TableStyleMedium1,
    TableStyleMedium2,
    TableStyleMedium3,
    TableStyleMedium4,
    TableStyleMedium5,
    TableStyleMedium6,
    TableStyleMedium7,
    TableStyleMedium8,
    TableStyleMedium9,
    TableStyleMedium10,
    TableStyleMedium11,
    TableStyleMedium12,
    TableStyleMedium13,
    TableStyleMedium14,
    TableStyleMedium15,
    TableStyleMedium16,
    TableStyleMedium17,
    TableStyleMedium18,
    TableStyleMedium19,
    TableStyleMedium20,
    TableStyleMedium21,
    TableStyleMedium22,
    TableStyleMedium23,
    TableStyleMedium24,
    TableStyleMedium25,
    TableStyleMedium26,
    TableStyleMedium27,
    TableStyleMedium28
}

public enum EFontName
{
    AbadiMT,
    AgencyFB,
    AharoniBold,
    Aldhabi,
    Algerian,
    AlmanacMT,
    AmericanUncial,
    AndaleMono,
    Andalus,
    Andy,
    AngsanaUPC,
    AngsanaNew,
    Aparajita,
    ArabicTransparent,
    ArabicTypesetting,
    Arial,
    ArialBlack,
    ArialNarrow,
    ArialNarrowSpecial,
    ArialRoundedMT,
    ArialSpecial,
    ArialUnicodeMS,
    AugsburgerInitials,
    AvenirNextLTPro,
    Bahnschrift,
    BaskervilleOldFace,
    BatangBatangChe,
    Bauhaus93,
    BeeskneesITC,
    BellMT,
    Bembo,
    BerlinSansFB,
    BernardMTCondensed,
    BickleyScript,
    Biome,
    BIZUDGothic,
    BIZUDMinchoMedium,
    BlackadderITC,
    BodoniMT,
    BodoniMTCondensed,
    BonApetitMT,
    BookmanOldStyle,
    BookshelfSymbol,
    BookAntiqua,
    BradleyHandITC,
    Braggadocio,
    BriemScript,
    BritannicBold,
    Broadway,
    BrowalliaUPC,
    BrowalliaNew,
    BrushScriptMT,
    Calibri,
    CalifornianFB,
    CalistoMT,
    Cambria,
    CambriaMath,
    Candara,
    Cariadings,
    Castellar,
    Cavolini,
    Centaur,
    Century,
    CenturyGothic,
    CenturySchoolbook,
    Chiller,
    ColonnaMT,
    ComicSansMS,
    Consolas,
    Constantia,
    ContemporaryBrush,
    CooperBlack,
    CopperplateGothic,
    Corbel,
    CordiaUPC,
    CordiaNew,
    CourierNew,
    CurlzMT,
    Dante,
    DaunPenh,
    David,
    Daytona,
    Desdemona,
    DFKaiSB,
    DilleniaUPC,
    DirectionsMT,
    DokChampa,
    DotumDotumChe,
    Ebrima,
    Eckmann,
    Edda,
    EdwardianScriptITC,
    Elephant,
    EngraversMT,
    Enviro,
    ErasITC,
    EstrangeloEdessa,
    EucrosiaUPC,
    Euphemia,
    Eurostile,
    FangSong,
    FelixTitling,
    FineHand,
    FixedMiriamTransparent,
    Flexure,
    FootlightMT,
    Forte,
    FranklinGothic,
    FranklinGothicMedium,
    FrankRuehl,
    FreesiaUPC,
    FreestyleScript,
    FrenchScriptMT,
    Futura,
    Gabriola,
    Gadugi,
    Garamond,
    GaramondMT,
    Gautami,
    Georgia,
    GeorgiaRef,
    Gigi,
    GillSansMT,
    GillSansMTCondensed,
    Gisha,
    Gloucester,
    GoudyOldStyle,
    GoudyStout,
    Gradl,
    Grotesque,
    GulimGulimChe,
    GungsuhGungsuhChe,
    HadassahFriedlaender,
    Haettenschweiler,
    HarlowSolidItalic,
    Harrington,
    HGGothicE,
    HGMinchoE,
    HGSoeiKakugothicUB,
    HighTowerText,
    HolidaysMT,
    HoloLensMDL2Assets,
    Impact,
    ImprintMTShadow,
    InformalRoman,
    IrisUPC,
    IskoolaPota,
    JasmineUPC,
    JavaneseText,
    Jokerman,
    JuiceITC,
    KaiTi,
    Kalinga,
    Kartika,
    KeystrokesMT,
    KhmerUI,
    Kigelia,
    KinoMT,
    KodchiangUPC,
    Kokila,
    KristenITC,
    KunstlerScript,
    LaoUI,
    Latha,
    LCD,
    Leelawadee,
    LevenimMT,
    LilyUPC,
    LucidaBlackletter,
    LucidaBright,
    LucidaBrightMath,
    LucidaCalligraphy,
    LucidaConsole,
    LucidaFax,
    LucidaHandwriting,
    LucidaSans,
    LucidaSansTypewriter,
    LucidaSansUnicode,
    Magneto,
    MaiandraGD,
    MalgunGothic,
    Mangal,
    MapSymbols,
    Marlett,
    MatisseITC,
    MaturaMTScriptCapitals,
    McZee,
    MeadBold,
    Meiryo,
    MercuriusScriptMTBold,
    MicrosoftGothicNeo,
    MicrosoftHimalaya,
    MicrosoftJhengHei,
    MicrosoftJhengHeiUI,
    MicrosoftNewTaiLue,
    MicrosoftPhagsPa,
    MicrosoftSansSerif,
    MicrosoftTaiLe,
    MicrosoftUighur,
    MicrosoftYaHei,
    MicrosoftYaHeiUI,
    MicrosoftYiBaiti,
    MingLiU,
    MingLiUExtB,
    MingLiU_HKSCS,
    MingLiU_HKSCSExtB,
    MinionWeb,
    Miriam,
    MiriamFixed,
    Mistral,
    ModernLove,
    ModernNo20,
    MongolianBaiti,
    Monotypecom,
    MonotypeCorsiva,
    MonotypeSorts,
    MoolBoran,
    MSGothic,
    MSLineDraw,
    MSMincho,
    MSOutlook,
    MSPGothic,
    MSPMincho,
    MSReference,
    MSUIGothic,
    MTExtra,
    MVBoli,
    MyanmarText,
    Narkisim,
    NewsGothicMT,
    NewCaledonia,
    Niagara,
    NirmalaUI,
    Nyala,
    OCRBDigits,
    OCRB,
    OCRAExtended,
    OldEnglishTextMT,
    Onyx,
    PalaceScriptMT,
    PalatinoLinotype,
    Papyrus,
    Parade,
    Parchment,
    PartiesMT,
    PeignotMedium,
    PepitaMT,
    Perpetua,
    PerpetuaTitlingMT,
    PlacardCondensed,
    PlantagenetCherokee,
    Playbill,
    PMingLiU,
    PMingLiUExtB,
    PoorRichard,
    Posterama,
    Pristina,
    QuireSans,
    Raavi,
    RageItalic,
    Ransom,
    Ravie,
    RefSpecialty,
    Rockwell,
    RockwellNova,
    Rod,
    RunicMTCondensed,
    SabonNextLT,
    Sagona,
    SakkalMajalla,
    ScriptMTBold,
    SegoeChess,
    SegoePrint,
    SegoeScript,
    SegoeUI,
    SegoeUISymbol,
    Selawik,
    ShonarBangla,
    ShowcardGothic,
    Shruti,
    SignsMT,
    SimHei,
    SimplifiedArabicFixed,
    SimSun,
    SimSunExtB,
    Sitka,
    NSimSun,
    SnapITC,
    SportsMT,
    STCaiyun,
    Stencil,
    STFangsong,
    STHupo,
    STKaiti,
    Stop,
    STXihei,
    STXingkai,
    STXinwei,
    STZhongsong,
    Sylfaen,
    Symbol,
    Tahoma,
    TempoGrunge,
    TempusSansITC,
    TempInstallerFont,
    TheHand,
    TheSerifHand,
    TimesNewRoman,
    TimesNewRomanSpecial,
    TisaOffcSerifPro,
    TraditionalArabic,
    TransportMT,
    TrebuchetMS,
    Tunga,
    TwCenMT,
    Univers,
    UrduTypesetting,
    Utsaah,
    VacationMT,
    Vani,
    Verdana,
    VerdanaRef,
    Vijaya,
    VinerHandITC,
    Vivaldi,
    VixarASCI,
    VladimirScript,
    Vrinda,
    Walbaum,
    Webdings,
    Westminster,
    WideLatin,
    Wingdings
}

public enum EIndexedExcelColors
{
    Black = 8,
    White = 9,
    Red = 10,
    BrightGreen = 11,
    Blue = 12,
    Yellow = 13,
    Pink = 14,
    Turquoise = 15,
    DarkRed = 16,
    Green = 17,
    DarkBlue = 18,
    DarkYellow = 19,
    Violet = 20,
    Teal = 21,
    Grey25Percent = 22,
    Grey50Percent = 23,
    CornflowerBlue = 24,
    Maroon = 25,
    LemonChiffon = 26,
    Orchid = 28,
    Coral = 29,
    RoyalBlue = 30,
    LightCornflowerBlue = 31,
    SkyBlue = 40,
    LightTurquoise = 41,
    LightGreen = 42,
    LightYellow = 43,
    PaleBlue = 44,
    Rose = 45,
    Lavender = 46,
    Tan = 47,
    LightBlue = 48,
    Aqua = 49,
    Lime = 50,
    Gold = 51,
    LightOrange = 52,
    Orange = 53,
    BlueGrey = 54,
    Grey40Percent = 55,
    DarkTeal = 56,
    SeaGreen = 57,
    DarkGreen = 58,
    OliveGreen = 59,
    Brown = 60,
    Plum = 61,
    Indigo = 62,
    Grey80Percent = 63
}
#pragma warning restore CRR0048 // The type name does not correspond to the file name
