# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zeshue/aspnet9-jammy-ffmpeg:1.0.2
      credentials:
        username: zeshue
        password: ${{ secrets.docker_hub_password }}

    steps:
    - uses: actions/checkout@v4
    - name: Get Curl
      run:  apt-get update && apt-get install -y curl

    - name: Add LibreOffice
      run: apt-get install libreoffice -y
    - name: Get Libre Office Version
      run: soffice --version
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
        
    - name: Add Fonts
      run: apt-get update && apt-get install -y fonts-dejavu fonts-liberation fonts-ubuntu
    - name: Add OptiPng
      run: apt-get install -y optipng
    - name: Add GifSicle
      run: apt-get install -y gifsicle
    - name: Add JpegOptim
      run: apt-get install -y jpegoptim
    - name: Update Font Cache
      run: fc-cache -f
    #- name: Add LibreOffice
    #  run: apt-get install libreoffice -y
    #- name: Get Libre Office Version
    #  run: soffice --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
